server:
  port: 7800
spring:
  application:
    name: config-app
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cybe-m1/microorder_config

management.endpoints.web.exposure.include: '*'