/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package fges.easyfoodtruck.service.api.controller;

import fges.easyfoodtruck.service.api.model.Error;
import java.util.List;
import fges.easyfoodtruck.service.api.model.MenutDTO;
import fges.easyfoodtruck.service.exception.FunctionalException;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "Menu", description = "the Menu API")
public interface MenuApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /v1/menu/add_product : add an ingredient in product id
     * add an ingredient in product id
     *
     * @param id id of the product (required)
     * @param requestBody  (optional)
     * @return Successful response - returns an Id. (status code 200)
     *         or Bad request (status code 400)
     */
    @ApiOperation(value = "add an ingredient in product id", nickname = "addProductInMenuId", notes = "add an ingredient in product id", response = MenutDTO.class, tags={ "Menu", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful response - returns an Id.", response = MenutDTO.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class) })
    @RequestMapping(value = "/v1/menu/add_product",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<MenutDTO> addProductInMenuId(@ApiParam(value = "id of the product" ,required=true) @RequestHeader(value="id", required=true) Integer id,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) List<String> requestBody) throws FunctionalException {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"name\" : \"name\", \"description\" : \"description\", \"id\" : 0, \"products\" : [ \"products\", \"products\" ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /v1/menu/add : create a menu
     * create a menu
     *
     * @param menutDTO  (optional)
     * @return Successful response -  returns   &#x60;MenutDTO&#x60; entities. (status code 200)
     *         or Bad request (status code 400)
     */
    @ApiOperation(value = "create a menu", nickname = "createMenu", notes = "create a menu", response = MenutDTO.class, tags={ "Menu", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful response -  returns   `MenutDTO` entities.", response = MenutDTO.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class) })
    @RequestMapping(value = "/v1/menu/add",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<MenutDTO> createMenu(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) MenutDTO menutDTO) throws FunctionalException {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"name\" : \"name\", \"description\" : \"description\", \"id\" : 0, \"products\" : [ \"products\", \"products\" ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /v1/menu/delete_product : delete a product Id in menu
     * delete a product id in menu
     *
     * @param id id of the ingredient (required)
     * @param requestBody  (optional)
     * @return Accepted. (status code 202)
     *         or Bad request (status code 400)
     */
    @ApiOperation(value = "delete a product Id in menu", nickname = "deleteProductIdInMenu", notes = "delete a product id in menu", tags={ "Menu", })
    @ApiResponses(value = {
        @ApiResponse(code = 202, message = "Accepted."),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class) })
    @RequestMapping(value = "/v1/menu/delete_product",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> deleteProductIdInMenu(@ApiParam(value = "id of the ingredient" ,required=true) @RequestHeader(value="id", required=true) Integer id,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) List<String> requestBody) throws FunctionalException {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /v1/menu/all : get all menus
     * get all menus
     *
     * @return Successful response - returns an array of &#x60;MenutDTO&#x60; entities. (status code 200)
     *         or Bad request (status code 400)
     */
    @ApiOperation(value = "get all menus", nickname = "getMenus", notes = "get all menus", response = MenutDTO.class, responseContainer = "List", tags={ "Menu", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Successful response - returns an array of `MenutDTO` entities.", response = MenutDTO.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class) })
    @RequestMapping(value = "/v1/menu/all",
        produces = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<List<MenutDTO>> getMenus() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"name\" : \"name\", \"description\" : \"description\", \"id\" : 0, \"products\" : [ \"products\", \"products\" ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
